# Generated by Django 4.0.4 on 2022-07-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word_list',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=1000)),
                ('meaning', models.CharField(max_length=1000)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.languages')),
            ],
        ),
    ]
