# Generated by Django 4.0.4 on 2022-07-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_remove_languages_country_word_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='country',
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
