# Generated by Django 4.0.4 on 2022-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_remove_languages_country_delete_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
