# Generated by Django 4.0.4 on 2022-07-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_languages_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='country',
        ),
    ]
