# Generated by Django 4.0.4 on 2022-07-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_rename_word_list_word_remove_languages_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Words',
        ),
    ]
