# Generated by Django 4.0.4 on 2022-07-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_rename_word_words_remove_languages_country'),
    ]

    operations = [

        migrations.AlterField(
            model_name='words',
            name='meaning',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=500),
        ),
    ]
