# Generated by Django 4.0.4 on 2022-07-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_remove_languages_country_alter_words_meaning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='meaning',
            field=models.CharField(max_length=2500),
        ),
    ]
